scheming_version: 3
dataset_type: site
about_url: https://pose.com/site

dataset_fields:

- field_name: title
  label: Title
  preset: title
  form_placeholder: eg. A Descriptive Title

- field_name: name
  label: URL
  preset: dataset_slug
  form_placeholder: eg. a-descriptive-title

- field_name: owner_org
  label: Organization
  required: True
  preset: dataset_organization

- field_name: notes
  label: Description
  required: True
  form_snippet: markdown.html
  form_placeholder: eg. Some useful notes about the data

# - field_name: group
#   label: Categories
#   preset: multiple_checkbox
#   choices_helper: scheming_groups_choices
#   required: False
#   help_text: Broad categories these data fall within. For data curation purposes, users should be a member of the category to add a dataset to the category.

- field_name: tag_string
  label: Tags
  preset: tag_string_autocomplete
  form_placeholder: eg. economy, mental health, government

- field_name: url
  label: External Link
  form_placeholder: eg. http://example.com
  required: True

- field_name: data_contact_email
  label: Contact Email
  form_placeholder: joe@example.com
  required: True
  display_snippet: email.html
  form_placeholder: Professional email for application questions or concerns.

- field_name: related_datasets
  label: Related Datasets
  preset: multiple_text

resource_fields:

- field_name: url
  label: Screenshot
  preset: resource_url_upload
  form_placeholder: http://example.com/my-application-screenshot.jpg
  upload_label: Photo

- field_name: name
  label: Caption
  validators: ignore_missing
  form_placeholder: eg. Description of application screenshot