scheming_version: 3
dataset_type: site
about: "Schema for describing CKAN instances with extended metadata"
about_url: "https://github.com/ckan/ckanext-scheming"

dataset_fields:

- field_name: title
  label: Site Name
  preset: title
  required: true
  help_text: The name of your CKAN site.

- field_name: name
  label: URL
  preset: dataset_slug

- field_name: owner_org
  label: Organization
  required: false
  preset: dataset_organization

- field_name: url
  label: Site URL
  validators: url_validator ignore_missing
  form_placeholder: Enter the URL of your CKAN site
  help_text: The URL of your CKAN site.

- field_name: public_site
  label: Public Site
  preset: select
  validators: ignore_missing
  choices:
    - label: "Yes - Publicly available"
      value: "true"
    - label: "No - Not publicly available"
      value: "false"
  help_text: Indicate if the site is publicly available.

- field_name: notes
  label: Description
  form_snippet: markdown.html
  required: true
  help_text: Tell us about your CKAN site, its purpose, and what kind of data it hosts.

- field_name: is_featured
  label: Is Featured
  preset: select
  validators: ignore_missing
  choices:
    - value: TRUE
      label: Yes
    - value: FALSE
      label: No
  help_text: Indicates whether the extension is marked as featured

- field_name: location
  label: Location
  required: false
  help_text: "e.g. 'Uruguay', 'Queensland, Australia', 'Hamburg, Germany'. Leave blank if your site has global scope or location does not apply."

- field_name: region
  label: Region
  preset: select
  validators: ignore_missing
  choices:
    - label: "North America"
      value: "North America"
    - label: "Latin America & Caribbean"
      value: "Latin America & Caribbean"
    - label: "Sub-Saharan Africa"
      value: "Sub-Saharan Africa"
    - label: "Global / Uncertain"
      value: "Global / Uncertain"
    - label: "Europe"
      value: "Europe"
    - label: "Asia-Pacific"
      value: "Asia-Pacific"
    - label: "North Africa & Middle East"
      value: "North Africa & Middle East"
    - label: "Central Asia"
      value: "Central Asia"
  help_text: "What region does your instance belong to?"

- field_name: latitude
  label: Latitude
  validators: ignore_missing 
  form_placeholder: "e.g. 51.5074"
  help_text: "The latitude coordinate of your location in decimal degrees (e.g. 51.5074 for London)"

- field_name: longitude
  label: Longitude
  validators: ignore_missing 
  form_placeholder: "e.g. -0.1278"
  help_text: "The longitude coordinate of your location in decimal degrees (e.g. -0.1278 for London)"

- field_name: site_type
  label: Type
  preset: select
  validators: ignore_missing
  choices:
    - label: "Commercial"
      value: "Commercial"
    - label: "Educational"
      value: "Educational"
    - label: "Government"
      value: "Government"
    - label: "Non-profit"
      value: "Non_profit"
    - label: "Research"
      value: "Research"
    - label: "Unknown"
      value: "Unknown"
  help_text: "The type of organization running the CKAN instance."

- field_name: status
  label: Status
  preset: select
  validators: ignore_missing
  choices:
    - label: "Production"
      value: "production"
    - label: "Staging"
      value: "staging"
    - label: "Development"
      value: "development"
  help_text: "The current status of your CKAN site."

# Technical Details
- field_name: git_repo
  label: Git Repository
  validators: url_validator ignore_missing
  validators: ignore_missing
  help_text: "Link to a public repository with your site customizations."

- field_name: ckan_version
  label: CKAN Version
  required: true
  help_text: "The version of CKAN you are running."

- field_name: extensions
  label: Extensions
  preset: multiple_text
  form_placeholder: Extensions
  help_text: "List any extensions you're using."

- field_name: contact_email
  label: Maintainer Email
  form_placeholder: Enter the maintainer email
  validators: ignore_missing
  help_text: Maintainer email for the site.

- field_name: tag_string
  label: Tags
  preset: tag_string_autocomplete
  form_placeholder: eg. economy, mental health, government

- field_name: language
  label: Primary Language
  preset: select
  validators: ignore_missing
  choices:
    - label: "English"
      value: "en"
    - label: "United Kingdom English"
      value: "en_GB"      
    - label: "French"
      value: "fr"
    - label: "Spanish"
      value: "es"
    - label: "German"
      value: "de"
    - label: "Italian"
      value: "it"
    - label: "Portuguese"
      value: "pt"
    - label: "Dutch"
      value: "nl"
    - label: "Swedish"
      value: "sv"
    - label: "Danish"
      value: "da"
    - label: "Finnish"
      value: "fi"
    - label: "Norwegian"
      value: "no"
    - label: "Polish"
      value: "pl"
    - label: "Czech"
      value: "cs"
    - label: "Slovak"
      value: "sk"
    - label: "Hungarian"
      value: "hu"
    - label: "Romanian"
      value: "ro"
    - label: "Bulgarian"
      value: "bg"
    - label: "Greek"
      value: "el"
    - label: "Latvian"
      value: "lv"
    - label: "Lithuanian"
      value: "lt"
    - label: "Estonian"
      value: "et"
    - label: "Slovenian"
      value: "sl"
    - label: "Croatian"
      value: "hr"
    - label: "Mexican Spanish"
      value: "es-mx"
    - label: "Argentinian Spanish"
      value: "es-ar"
    - label: "Chilean Spanish"
      value: "es-cl"
    - label: "Brazilian Portuguese"
      value: "pt-br"
    - label: "Canadian French"
      value: "fr-ca"
    - label: "Chinese"
      value: "zh"
    - label: "Japanese"
      value: "ja"
    - label: "Korean"
      value: "ko"
    - label: "Thai"
      value: "th"
    - label: "Vietnamese"
      value: "vi"
    - label: "Indonesian"
      value: "id"
    - label: "Malay"
      value: "ms"
    - label: "Hindi"
      value: "hi"
    - label: "Bengali"
      value: "bn"
    - label: "Urdu"
      value: "ur"
    - label: "Persian"
      value: "fa"
    - label: "Arabic"
      value: "ar"
    - label: "Hebrew"
      value: "he"
    - label: "Turkish"
      value: "tr"
    - label: "Swahili"
      value: "sw"
    - label: "Amharic"
      value: "am"
    - label: "Hausa"
      value: "ha"
    - label: "Yoruba"
      value: "yo"
    - label: "Zulu"
      value: "zu"
    - label: "Other"
      value: "other"
  help_text: "Primary language of the Website"



- field_name: num_datasets
  label: Number of Datasets
  validators: ignore_missing int_validator
  form_placeholder: "e.g. 1024"
  help_text: "Total number of datasets in this CKAN instance"

- field_name: num_organizations
  label: Number of Organizations
  validators: ignore_missing int_validator
  form_placeholder: "e.g. 42"
  help_text: "Total numchoicesber of organizations in this CKAN instance"

- field_name: num_groups
  label: Number of Groups
  validators: ignore_missing int_validator
  form_placeholder: "e.g. 15"
  help_text: "Total number of groups in this CKAN instance"

- field_name: topic_id
  label: Topic ID
  validators: ignore_missing
  form_placeholder: Enter the topic ID
  help_text: Unique identifier for the extensions topic

resource_fields:
- field_name: url
  label: Screenshot
  preset: resource_url_upload
  validators: ignore_missing
  form_placeholder: http://example.com/my-application-screenshot.jpg
  upload_label: Photo

- field_name: name
  label: Caption
  validators: ignore_missing
  form_placeholder: eg. Description of application screenshot
  required: false
